# Generated by Django 4.0.1 on 2022-03-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userviewapp', '0004_addcartdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addcartdb',
        ),
    ]
