# Generated by Django 4.0.1 on 2022-03-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userviewapp', '0005_delete_addcartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
