# Generated by Django 4.0.1 on 2022-03-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userviewapp', '0008_remove_checkout_userid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='checkout',
            new_name='Checkoutdb',
        ),
    ]
