# Generated by Django 4.0.1 on 2022-03-08 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_productdb_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='weight',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
