# Generated by Django 4.0.1 on 2022-04-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0005_alter_productdb_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
